### ISSUE TITLE
Manager prints the charts

### ISSUE THREAD

**Issue by franpog859** [paulinaurbas/BD-Car-Dealerships-Managment-System#1]
As a manager, I want to have charts representing:
- how much income the company generates presented by weeks
- which car brands do we sell the most 
- how many cars we sell in comparison to how many cars we buy
- what percentage of cars need to be serviced before selling
- how many workers of different types there is hired in the company

These are the basic things I need to do while managing the company

**Acceptance Criteria**
- [x] manager can see all mentioned charts using frontend
- [x] server can prepare data necessary for charts using the database
- [x] README is updated with a tutorial on how to open the manager tab with all charts

**Comment by franpog859** [comment]
I wanted to elaborate on my suggestions a little bit more:
- how much income the company generates presented by weeks
  - HISTOGRAM
  - Y axis: income summed and grouped by weeks
  - X axis: dates grouped by weeks
- which car brands do we sell the most
  - PIE CHART
  - angle: number of sold cars summed and grouped by brands
- how many cars we sell in comparison to how many cars we buy
  - LINEAR CHART (two lines - one for sold cars, one for bought cars)
  - Y axis: number of cars
  - X axis: dates grouped by weeks
- what percentage of cars need to be serviced before selling
  - PIE CHART
  - angle: number of cars that need to be serviced and that do not need to
- how many workers of different types there is hired in the company
  - PIE CHART
  - angle: number of workers summed and grouped by worker type

What do you think?

**Comment by paulinaurbas** [comment]
exelent 👍
