### ISSUE TITLE
Create consistent UI

### ISSUE THREAD

**Issue by franpog859** [paulinaurbas/BD-Car-Dealerships-Managment-System#18]
As a user, I want to see the app with consistent and beautiful UI!

**Acceptance Criteria**
- [x] favicon is added to the project
- [x] the main banner is created
- [x] UI is refactored and looks wonderful
- [x] README with the tutorials is updated if anything was changed

**EDIT:**
> @paulinaurbas : can we add help page, error prevention and frontend handling error to this story?
- [x] the help page is added
- [x] frontend errors are handled properly without breaking the application

**Comment by paulinaurbas** [comment]
**UXUI things to do:** 
- help page 
- error prevention and frontend handling error
 
**UXUI things we have:** 
- consistency and standards
- RWD variant A 
- Main site F pattern, after login site -> Z pattern 

@franpog859 can we add help page, error prevention and frontend handling error to this story?

**Comment by franpog859** [comment]
@paulinaurbas , sure! I just updated the issue description 👍

**Comment by paulinaurbas** [comment]
@franpog859  thank you 👍
